### ISSUE TITLE
Sin Pacientes & Log In

### ISSUE THREAD

**Issue by MarcoRob** [FunDeDiseno/federacionHemofilia#5]
Poner un mensaje de alerta explicando el porque no hay pacientes y que hay que registrarlos

Tambien cambiar el link para cuando inicie sesion un Doctor se direccione a la pagina .../Doctor/Inicio

**Comment by miker1423** [comment]
listo, se solucionó el commit 31704e8093f3a7bc390bf4e27806295ead13980a
